### ISSUE TITLE
Dependabot Upgrade does not work well

### ISSUE THREAD

**Issue by takasehideki** [tlk-emb/rclex_samples#10]
Although we upgraded Dependabot in #8, it does not work well now. We need to investigate the causes.

**Comment by takasehideki** [comment]
ref: official doc
https://docs.github.com/ja/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot

**Comment by takasehideki** [comment]
I've uninstalled Dependabot-preview in this organization because it will be deactivated.

**Comment by takasehideki** [comment]
According to official doc, just we need to do is creating `./github/dependabot.yml`. We've already create it,,,

**Comment by takasehideki** [comment]
Oh, I found the error log on "Insights -> Dependency graph -> Dependabot".

```
  proxy | time="2021-06-10T01:43:37Z" level=info msg="proxy starting" commit=304578065486d2785724ade6ca14646dfb7314a5
  proxy | 2021/06/10 01:43:37 Listening (:1080)
updater | 2021-06-10T01:43:37.200149299 [155256575:main:WARN:src/devices/src/legacy/serial.rs:434] Detached the serial input due to peer close/error.
updater | time="2021-06-10T01:43:38Z" level=info msg="guest starting" commit=851a346ff620d6e87a6fca263dfa6630f58c9603
updater | time="2021-06-10T01:43:38Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=155256575 updater_timeout=45m0s updater_version=0.151.1-2db3ae576331e5d67920347e135a3d4b0ada9e39
updater | I, [2021-06-10T01:43:40.316744 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby26, which recognizes
updater | warning: 2.6.7-compliant syntax, but you are running 2.6.6.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_155256575> Starting job processing
  proxy | 2021/06/10 01:43:42 [002] GET https://api.github.com:443/repos/rclex/rclex_samples
  proxy | 2021/06/10 01:43:42 [002] * authenticating github api request
  proxy | 2021/06/10 01:43:42 [002] 200 https://api.github.com:443/repos/rclex/rclex_samples
  proxy | 2021/06/10 01:43:42 [004] GET https://api.github.com:443/repos/rclex/rclex_samples/git/refs/heads/main
  proxy | 2021/06/10 01:43:42 [004] * authenticating github api request
  proxy | 2021/06/10 01:43:42 [004] 200 https://api.github.com:443/repos/rclex/rclex_samples/git/refs/heads/main
  proxy | 2021/06/10 01:43:42 [006] GET https://api.github.com:443/repos/rclex/rclex_samples/contents/mix.exs?ref=0a4b7891699249f324fa7bbacff37d6adf5543c6
  proxy | 2021/06/10 01:43:42 [006] * authenticating github api request
  proxy | 2021/06/10 01:43:42 [006] 200 https://api.github.com:443/repos/rclex/rclex_samples/contents/mix.exs?ref=0a4b7891699249f324fa7bbacff37d6adf5543c6
  proxy | 2021/06/10 01:43:42 [008] GET https://api.github.com:443/repos/rclex/rclex_samples/contents/mix.lock?ref=0a4b7891699249f324fa7bbacff37d6adf5543c6
  proxy | 2021/06/10 01:43:42 [008] * authenticating github api request
  proxy | 2021/06/10 01:43:42 [008] 200 https://api.github.com:443/repos/rclex/rclex_samples/contents/mix.lock?ref=0a4b7891699249f324fa7bbacff37d6adf5543c6
updater | INFO <job_155256575> Finished job processing
updater | time="2021-06-10T01:43:43Z" level=info msg="task complete" container_id=job-155256575-file-fetcher exit_code=0 job_id=155256575 step=fetcher
updater | I, [2021-06-10T01:43:44.045711 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby26, which recognizes
updater | warning: 2.6.7-compliant syntax, but you are running 2.6.6.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_155256575> Starting job processing
updater | INFO <job_155256575> Starting update job for rclex/rclex_samples
updater | INFO <job_155256575> Checking if rclex 0.3.1 needs updating
  proxy | 2021/06/10 01:43:51 [012] GET https://hex.pm:443/api/packages/rclex
  proxy | 2021/06/10 01:43:51 [012] 200 https://hex.pm:443/api/packages/rclex
updater | INFO <job_155256575> Latest version is 0.4.0
updater | I, [2021-06-10T01:43:51.551891 #8]  INFO -- sentry: ** [Raven] Sending event 1475edbb60b54fb9a977feffd020eb91 to Sentry
  proxy | 2021/06/10 01:43:51 [014] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/06/10 01:43:51 [014] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_155256575> Error processing rclex (RuntimeError)
updater | ERROR <job_155256575> Expected content to change!
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/file_updater/mixfile_requirement_updater.rb:23:in `updated_content'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker/file_preparer.rb:77:in `relax_version'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker/file_preparer.rb:59:in `mixfile_content_for_update_check'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker/file_preparer.rb:32:in `block in prepared_dependency_files'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker/file_preparer.rb:29:in `map'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker/file_preparer.rb:29:in `prepared_dependency_files'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker.rb:205:in `prepared_dependency_files'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker.rb:184:in `version_resolver'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker.rb:176:in `fetch_latest_resolvable_version'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-hex-0.151.1/lib/dependabot/hex/update_checker.rb:32:in `latest_resolvable_version'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.151.1/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.151.1/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.151.1/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.151.1/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.151.1/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:429:in `requirements_to_unlock'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:224:in `check_and_create_pull_request'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_155256575> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_155256575> bin/update_files.rb:21:in `<main>'
updater | INFO <job_155256575> Finished job processing
updater | time="2021-06-10T01:43:52Z" level=info msg="task complete" container_id=job-155256575-updater exit_code=0 job_id=155256575 step=updater
```

**Comment by takasehideki** [comment]
The cause may be a bad style of `deps:` in `mix.exs`.
I fixed the style at 4a26765 
https://github.com/rclex/rclex_samples/commit/4a2676526e103bacfda8d225d320fd424ad4662e#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308

**Comment by takasehideki** [comment]
I will close this issue the next time Dependabot comes here :D

**Comment by takasehideki** [comment]
I think `@version` could not be treat by Dependabot,,, 
https://github.com/rclex/rclex_samples/blob/main/mix.exs#L26
